family: <ENVIRONMENT>-<APP_NAME>-task
networkMode: awsvpc
requiresCompatibilities:
  - FARGATE
cpu: "256"
memory: "512"
executionRoleArn: <ECS_TASK_EXECUTION_ROLE_ARN>
taskRoleArn: <ECS_TASK_ROLE_ARN>
containerDefinitions:
  - name: <ENVIRONMENT>-<APP_NAME>-container
    image: <APP_IMAGE>
    essential: true
    portMappings:
      - containerPort: 3000
        protocol: tcp
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: /ecs/<ENVIRONMENT>-<APP_NAME>-app
        awslogs-region: <AWS_REGION>
        awslogs-stream-prefix: ecs
    Environment:
      - name: NODE_ENV
        value: "<ENVIRONMENT>"
      - name: PORT
        value: "3000"
