version: "3"

# Run: task <name>
tasks:
  core.deploy:
    desc: Deploy ECS Core using SAM
    cmds:
      - sam package --config-env core --config-file ../samconfig.yaml
      - sam deploy --config-env core --config-file ../samconfig.yaml --no-fail-on-empty-changeset

  task.deploy:
    desc: Deploy ECS Task using SAM
    cmds:
      - sam package --config-env task --config-file ../samconfig.yaml
      - sam deploy --config-env task --config-file ../samconfig.yaml --no-fail-on-empty-changeset

  blue-green-pipeline-codedeploy.deploy:
    desc: Deploy ECS Pipeline using SAM
    cmds:
      - sam package --config-env blue-green-pipeline-codedeploy --config-file ../samconfig.yaml
      - sam deploy --config-env blue-green-pipeline-codedeploy --config-file ../samconfig.yaml --no-fail-on-empty-changeset
