version: 0.1

core:
  package:
    parameters:
      s3_bucket: faboulaye-sandbox-sam-repository
      s3_prefix: ecs-platform
      region: eu-central-1
      template_file: ecs-core.yaml
      output_template_file: ecs-core-out.yaml
      profile: faboulaye-sandbox
  deploy:
    parameters:
      s3_bucket: faboulaye-sandbox-sam-repository
      s3_prefix: ecs-platform
      region: eu-central-1
      stack_name: test-host-info-app-ecs-core
      confirm_changeset: false
      capabilities: CAPABILITY_IAM CAPABILITY_NAMED_IAM
      template_file: ecs-core-out.yaml
      parameter_overrides:
        - VpcId=vpc-0eba91cb02d447273
        - SubnetId1=subnet-00baa81f37ac412d3
        - SubnetId2=subnet-0bda715ccc59dd47c
      tags:
        - Project=devops-ecs-deployment
      profile: faboulaye-sandbox

pipeline:
  package:
    parameters:
      s3_bucket: faboulaye-sandbox-sam-repository
      s3_prefix: ecs-platform
      region: eu-central-1
      template_file: cd-pipeline.yaml
      output_template_file: cd-pipeline-out.yaml
      profile: faboulaye-sandbox
  deploy:
    parameters:
      s3_bucket: faboulaye-sandbox-sam-repository
      s3_prefix: ecs-platform
      region: eu-central-1
      stack_name: host-info-app-cd-pipeline
      confirm_changeset: false
      capabilities: CAPABILITY_IAM CAPABILITY_NAMED_IAM
      template_file: cd-pipeline-out.yaml
      parameter_overrides:
        - AppEcrRepositoryUri=244086559228.dkr.ecr.eu-central-1.amazonaws.com/test-host-info-app-repo
      tags:
        - Project=devops-ecs-deployment
      profile: faboulaye-sandbox
